# Generated by Django 5.1 on 2024-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('blockOfFlats', 'Block of Flats'), ('apartmentBuilding', 'Apartment Building'), ('tenement', 'Tenement')], max_length=100)),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('floor_count', models.IntegerField()),
                ('build_year', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centre_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poi_count', models.IntegerField()),
                ('school_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clinic_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('post_office_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kindergarten_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('restaurant_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('college_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pharmacy_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownership', models.CharField(choices=[('condominium', 'Condominium'), ('udział', 'Udział'), ('cooperative', 'Cooperative')], max_length=100)),
                ('building_material', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('premium', 'Premium'), ('low', 'Low')], max_length=100)),
                ('has_parking_space', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_storage_room', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='properties', to='property.propertyimage')),
            ],
        ),
    ]
