# Generated by Django 5.1 on 2024-08-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproperty',
            name='clinic_distance',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='college_distance',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='kindergarten_distance',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='pharmacy_distance',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='post_office_distance',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='restaurant_distance',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='school_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='clinic_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='college_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kindergarten_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pharmacy_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='post_office_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='restaurant_distance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='school_distance',
        ),
    ]
