# Generated by Django 5.1 on 2024-08-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_options_alter_property_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
