# Generated by Django 5.1 on 2024-08-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_centre_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproperty',
            old_name='address',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
